### ISSUE TITLE
List of enums

### ISSUE THREAD

**Issue by ryango** [Instagram/ig-json-parser#27]
Seems to not work. Might be doing something wrong in the annotation

@JsonField(fieldName = "test_list",
valueExtractFormatter = "TestObject.TestEnum.valueOf(${parser_object}.getText())",
fieldAssignmentFormatter = "${object_varname}.${field_varname} = ${extracted_value}",
serializeCodeFormatter = "${generator_object}.writeStringField(\"${json_fieldname}\", ${iterator}.toString())")
public List<TestEnum> testList;

error: annotation exception: java.lang.IllegalStateException: Could not divine java type for test_list in class com.example.TestObject
    at com.instagram.common.json.annotation.processor.JsonParserClassData.getJavaType(JsonParserClassData.java:407)
    at com.instagram.common.json.annotation.processor.JsonParserClassData.generateArrayParser(JsonParserClassData.java:324)
    at com.instagram.common.json.annotation.processor.JsonParserClassData.generateCollectionParser(JsonParserClassData.java:315)
    at com.instagram.common.json.annotation.processor.JsonParserClassData.writeFields(JsonParserClassData.java:275)
    at com.instagram.common.json.annotation.processor.JsonParserClassData.access$000(JsonParserClassData.java:40)
    at com.instagram.common.json.annotation.processor.JsonParserClassData$1.emitJava(JsonParserClassData.java:159)

**Comment by ttung** [comment]
Collection types must be fully specified, like, `List<String>`.

**Comment by ryango** [comment]
Sorry, was sanitizing my code and typed it improperly. It's List<TestEnum>

**Comment by ryango** [comment]
Forgot to escape my \<\>. Get's filtered by markdown. Code that is failing has List\<TestEnum\>

**Comment by ttung** [comment]
Hard to say without more of your sample.  There's a unit test that covers enums, so it has to work at least somewhat.  https://github.com/Instagram/ig-json-parser/blob/master/processor/testuut/src/main/java/com/instagram/common/json/annotation/processor/EnumUUT.java

**Comment by aimango** [comment]
This was fixed in #60
